### ISSUE TITLE
Missing PDF files

### ISSUE THREAD

**Issue by juanramonduarte** [hertze/Filofax-todo#1]
Hi, 
I was really glad to find your repository recently.  I've been looking to create custom pages for my personal Filofax and your project seems like a great starting point.  

I see that the source references a few PDF files that are not in the repository:  

```
clockface.pdf
compass.pdf
book.pdf
checkbox-10mm.pdf
checkbox-4mm.pdf
checkbox-6mm.pdf
largebox.pdf
mediumbox.pdf
```

Seeing that it's been a few years since the last commit I wonder if you still have these and could share them?

Also, do you have a PDF version of the tex file to see what the originally intended output was?

Regards,
JRD

**Comment by hertze** [comment]
Hi! Thanks for dropping by! I've added the missing PDFs, as well as a rendered version of the tex file. I Hope that helps!

**Comment by juanramonduarte** [comment]
Amazing!!  Thanks for such a quick reply!  I'll review and see if I can make any contributions.
JRD

**Comment by hertze** [comment]
Perfect! Thanks!

Joakim
